name-template: 'v$RESOLVED_VERSION'
tag-template: '$RESOLVED_VERSION'
categories:
  - title: 'New Features'
    labels:
      - 'type: new feature'
  - title: 'Updates'
    labels:
      - 'type: enhancement'
  - title: 'Bug Fixes'
    labels:
      - 'type: bug'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'version: major'
  minor:
    labels:
      - 'version: minor'
  patch:
    labels:
      - 'version: patch'
  default: patch
template: |
  ## What Changed?

  $CHANGES
