name: ModuCoreBukkit
main: dev.jaims.moducore.bukkit.ModuCore
version: @version@
api-version: 1.16
author: Jaimss
depend: [ PlaceholderAPI, Vault ]
description: "A Modular and Customizable Core Plugin"

commands:
  # economy
  balance:
    aliases: [ money, bal ]
    description: "Check balance"
  economy:
    aliases: [ eco ]
    description: "Manage economy"
  pay:
    description: "Pay someone"
  # gamemode
  gma:
    aliases: [ gamemodeadventure ]
    description: "Set your or a target's gamemode to adventure."
  gmc:
    aliases: [ gamemodecreative ]
    description: "Set your or a target's gamemode to creative."
  gmsp:
    aliases: [ gamemodespectator ]
    description: "Set your or a target's gamemode to spectator."
  gms:
    aliases: [ gamemodesurvival ]
    description: "Set your or a target's gamemode to survival."
  # nick
  nickname:
    aliases: [ nick ]
    description: "Set your nickname"
  unnick:
    description: "Unset your nickname"
  # repair
  repair:
    description: "Repair items"
  repairall:
    description: "Repair all items"
  # speed
  setspawn:
    description: "set the spawn"
  spawn:
    description: "go to spawn"
  # speed
  flyspeed:
    description: "Change your flyspeed"
  speed:
    description: "Change the speed of you if you are flying/walking"
  walkspeed:
    description: "Change your walkspeed"
  # teleport
  teleport:
    aliases: [ tp ]
    description: " Teleport"
  teleporthere:
    aliases: [ tphere ]
    description: "Teleport a player to you"
  teleportplayer2player:
    aliases: [ tp2p ]
    description: "Teleport a player to another player"
  teleportposition:
    aliases: [ tppos ]
    description: "Teleport to a position"
  randomteleport:
    aliases: [ rtp ]
    description: "Randomly Teleport"
  # warp
  setwarp:
    description: "set a warp"
  deletewarp:
    aliases: [ delwarp ]
    description: "delete a warp"
  warp:
    description: "warp"
  # clear
  clear:
    aliases: [ ci,clearinventory ]
    description: "Clear your or a target's inventory."
  # dispose
  dispose:
    aliases: [ disposal,trash ]
    description: "Get rid of extra items."
  # feed
  feed:
    description: "Feed yourself or a target."
  # fly
  fly:
    description: "Enable flight for yourself or a target."
  # give
  give:
    aliases: [ i,giveitem ]
    description: "Give an item to yourself or a target."
  # heal
  heal:
    description: "Heal yourself or a target."
  # help
  help:
    description: "Show help pages."
  # dump
  moducoredump:
    description: "Dump to paste."
  # ping
  ping:
    description: "Ping people"
  # reload
  moducorereload:
    aliases: [ mcrl ]
    description: "Reload moducore and all of its files"
  # sudo
  sudo:
    aliases: [ commandproxy ]
    description: "Run as other player"
  # tps
  tps:
    description: "Check server tps"
  # time
  time:
    description: "Check server time"
  # weather
  weather:
    description: "Check server weather"

permissions:
  # admin perms
  moducore.admin:
    default: op
    description: "Access to everything"
  ########################
  ### COMMANDS SECTION ###
  ########################
  moducore.command.silent:
    default: op
  moducore.command.runwithsigns:
    default: op
  moducore.command.cooldown.bypass:
    default: op
  # economy commands
  moducore.command.balance:
    default: op
  moducore.command.balance.others:
    default: op
  moducore.command.economy:
    default: op
  moducore.command.pay:
    default: op
  # gamemode commands
  moducore.command.gamemode.survival:
    default: op
  moducore.command.gamemode.creative:
    default: op
  moducore.command.gamemode.adventure:
    default: op
  moducore.command.gamemode.spectator:
    default: op
  moducore.command.gamemode.survival.others:
    default: op
  moducore.command.gamemode.creative.others:
    default: op
  moducore.command.gamemode.adventure.others:
    default: op
  moducore.command.gamemode.spectator.others:
    default: op
  # nick
  moducore.command.nickname:
    default: op
  moducore.command.nickname.others:
    default: op
  moducore.command.unnick:
    default: op
  moducore.command.unnick.others:
    default: op
  # repair
  moducore.command.repair:
    default: op
  moducore.command.repair.others:
    default: op
  moducore.command.repairall:
    default: op
  moducore.command.rapairall.others:
    default: op
  # spawn
  moducore.command.setspawn:
    default: op
  moducore.command.spawn:
    default: op
  moducore.command.spawn_others:
    default: op
  # speed
  moducore.command.flyspeed:
    default: op
  moducore.command.flyspeed.others:
    default: op
  moducore.command.walkspeed:
    default: op
  moducore.command.walkspeed.others:
    default: op
  # teleport
  moducore.command.teleport:
    default: op
  moducore.command.teleport_player_to_player:
    default: op
  moducore.command.teleport_here:
    default: op
  moducore.command.teleport_pos:
    default: op
  moducore.command.random_teleport:
    default: op
  moducore.command.random_teleport.others:
    default: op
  # warp
  moducore.warp.<name>:
    default: op
  moducore.command.setwarp:
    default: op
  moducore.command.delwarp:
    default: op
  moducore.command.warp:
    default: op
  mdoucore.command.warp_others:
    default: op
  # clear
  moducore.command.clear:
    default: op
  moducore.command.clear.others:
    default: op
  # dispose
  moducore.command.dispose:
    default: op
  # feed
  moducore.command.feed:
    default: op
  moducore.command.feed.others:
    default: op
  # fly
  moducore.command.fly:
    default: op
  moducore.command.fly.others:
    default: op
  # give
  moducore.command.give:
    default: op
  moducore.command.give.others:
    default: op
  # heal
  moducore.command.heal:
    default: op
  moducore.command.heal.others:
    default: op
  # ping
  moducore.commnad.ping:
    default: op
  moducore.commnad.ping.others:
    default: op
  # dump
  moducore.command.dump:
    default: op
  # reload
  moducore.command.reload:
    default: op
  # time
  moducore.command.time:
    default: op
  # weather
  moducore.command.weather:
    default: op
  ####################
  ### CHAT SECTION ###
  ####################
  # markdown
  moducore.chat.markdown.bold:
    default: op
  moducore.chat.markdown.italic:
    default: op
  moducore.chat.markdown.strikethrough:
    default: op
  moducore.chat.markdown.underline:
    default: op
  moducore.chat.markdown.obfuscated:
    default: op
  moducore.chat.markdown.color:
    default: op
  moducore.chat.markdown.hex:
    default: op
  moducore.chat.markdown.gradient:
    default: op
  moducore.chat.markdown.rainbow:
    default: op
  moducore.chat.markdown.actions:
    default: op
  # set a default chat color
  moducore.chat.defaultcolor:
    default: op
  # access to different colors
  moducore.chat.color.purple:
    default: op
  moducore.chat.color.magenta:
    default: op
  moducore.chat.color.pink:
    default: op
  moducore.chat.color.cyan:
    default: op
  moducore.chat.color.lightblue:
    default: op
  moducore.chat.color.blue:
    default: op
  moducore.chat.color.lime:
    default: op
  moducore.chat.color.green:
    default: op
  moducore.chat.color.red:
    default: op
  moducore.chat.color.orange:
    default: op
  moducore.chat.color.yellow:
    default: op
  moducore.chat.color.brown:
    default: op
  moducore.chat.color.lightgray:
    default: op
  moducore.chat.color.gray:
    default: op
  moducore.chat.color.black:
    default: op
  moducore.chat.color.white:
    default: op